# Site Settings
title: "Muhammad Husnain Mubarik"
name: "Muhammad Husnain Mubarik"
description: "Personal Academic Website"
url: https://husnainmubarik.github.io
baseurl: ""
repository: "husnainmubarik/husnainmubarik.github.io"

# Use remote theme instead of storing all theme files
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Author
author:
  name: "Muhammad Husnain Mubarik"
  avatar: "/images/husnain_profile.jpg"
  bio: "Senior Member of Technical Staff @ AMD"
  location: "AMD"
  email: "mubarik3@illinois.edu"
  uri: "https://scholar.google.com/citations?user=Bz0xVZAAAAAJ&hl=en"
  github: "husnainmubarik"
  linkedin: "husnain-mubarik"
  twitter: "HusnainMubarik"

# Reading Files
include:
  - _pages
  - files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# Markdown
markdown: kramdown
highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# Timezone
timezone: America/Los_Angeles
